"""
HALF-CICD Agent (Phase 4B)

Generates CI/CD pipeline configurations with per-stage gates and deployment workflows.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path


class CICDAgent:
    """Phase 4B: CI/CD pipeline generation."""

    CI_WORKFLOW = """\
# Generated by HALF-CICD
name: CI

on:
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install ruff
      - run: ruff check src/ tests/

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install mypy
      - run: mypy src/

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install uv && uv sync
      - run: pytest --cov=src/ --cov-fail-under=80 --asyncio-mode=auto
        env:
          DATABASE_URL: postgresql+asyncpg://app:test@localhost:5432/app_test
          REDIS_URL: redis://localhost:6379/0

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install bandit semgrep
      - run: bandit -r src/ -ll
      - run: semgrep --config=auto --error src/

  build:
    needs: [lint, type-check, test, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t app:${{ github.sha }} .
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker tag app:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
      - run: docker push ghcr.io/${{ github.repository }}:latest
"""

    CD_WORKFLOW = """\
# Generated by HALF-CICD
name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main, master]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging
        run: |
          docker compose up -d --wait
          echo "Staging deployment complete"
      - name: Smoke tests
        run: |
          apt-get update && apt-get install -y curl
          curl -f http://localhost:8000/health || exit 1
          echo "Smoke tests passed"

  deploy-production:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: echo "Production deployment requires manual approval via HALF Finality Gate"
"""

    def __init__(self, target_dir: Path):
        self.target_dir = target_dir

    def generate_ci(self) -> str:
        """Generate ci.yml workflow."""
        workflows_dir = self.target_dir / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)

        filepath = workflows_dir / "ci.yml"
        filepath.write_text(self.CI_WORKFLOW)
        return str(filepath)

    def generate_cd(self) -> str:
        """Generate cd.yml workflow."""
        workflows_dir = self.target_dir / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)

        filepath = workflows_dir / "cd.yml"
        filepath.write_text(self.CD_WORKFLOW)
        return str(filepath)

    def generate_security_scan(self) -> str:
        """Generate weekly security scan workflow."""
        content = """\
name: Weekly Security Scan

on:
  schedule:
    - cron: "0 6 * * 1"  # Every Monday at 6AM UTC
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - run: pip install bandit semgrep pip-audit
      - run: bandit -r src/ -f json -o bandit-report.json
      - run: semgrep --config=auto src/ --json -o semgrep-report.json
      - run: pip-audit
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            semgrep-report.json
"""
        workflows_dir = self.target_dir / ".github" / "workflows"
        filepath = workflows_dir / "security-scan.yml"
        filepath.write_text(content)
        return str(filepath)
