"""
HALF-Observe Agent (Phase 5A)

Production monitoring loop configuration and anomaly detection.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class MonitoringRule:
    """A monitoring rule that triggers on condition."""

    name: str
    condition: str
    action: str
    severity: str = "info"  # info, warning, critical


@dataclass
class ObservationConfig:
    """Configuration for the monitoring loop."""

    metric_interval_seconds: int = 900  # 15m
    log_interval_seconds: int = 3600  # 1h
    health_interval_seconds: int = 300  # 5m
    anomaly_interval_seconds: int = 3600  # 1h

    rules: list[MonitoringRule] = field(
        default_factory=lambda: [
            MonitoringRule(
                name="error_rate_spike",
                condition="error_rate > 5% for 5 minutes",
                action="collect last 100 error logs, correlate with recent deployments",
                severity="critical",
            ),
            MonitoringRule(
                name="performance_degradation",
                condition="p95 latency > 2x baseline for 10 minutes",
                action="check resource usage and dependency health",
                severity="warning",
            ),
            MonitoringRule(
                name="coverage_drop",
                condition="coverage < 80%",
                action="identify uncovered code, generate tests, create PR",
                severity="warning",
            ),
        ]
    )


class ObserveAgent:
    """Phase 5A: Production monitoring loop setup."""

    def __init__(self, config: ObservationConfig | None = None):
        self.config = config or ObservationConfig()

    def render_monitoring_config_yaml(self) -> str:
        """Render monitoring configuration as YAML."""
        lines = [
            "# HALF Production Monitoring Configuration",
            "# Generated by HALF-Observe",
            "",
            "monitoring:",
            f'  metric_collection: "every {self.config.metric_interval_seconds // 60}m"',
            f'  log_analysis: "every {self.config.log_interval_seconds // 60}m"',
            f'  health_check: "every {self.config.health_interval_seconds // 60}m"',
            f'  anomaly_detection: "every {self.config.anomaly_interval_seconds // 60}m"',
            "",
            "triggers:",
        ]
        for rule in self.config.rules:
            lines.extend(
                [
                    f"  {rule.name}:",
                    f'    condition: "{rule.condition}"',
                    f"    severity: {rule.severity}",
                    "    action: |",
                    f"      {rule.action}",
                ]
            )
        return "\n".join(lines)

    @staticmethod
    def get_metrics_endpoints() -> dict[str, str]:
        """Get standard Prometheus metric endpoint configurations."""
        return {
            "custom_metrics": "/metrics",
            "health": "/health",
            "readiness": "/ready",
        }

    @staticmethod
    def get_alert_rules() -> str:
        """Get Prometheus alerting rules YAML."""
        return """\
groups:
  - name: half-production-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Error rate > 5% for 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "p95 latency > 500ms for 10 minutes"

      - alert: HighDiskUsage
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage > 80%"
"""
