"""HALF — AI-DECLARATION.md Generator.

Generates the AI-DECLARATION.md manifest during Phase 4 deployment.
This document specifies the exact level of AI involvement using standardized
tags and serves as the single source of truth for downstream auditors.

Based on the HALF doctrine's 'AI-Declaration Standard' specification.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger("half.ai_declaration")


# Standard declaration tags per the open standard
DECLARATION_LEVELS = {
    "auto": "Code was autonomously generated by an AI agent with human oversight at checkpoints",
    "pair": "Code was co-written by human and AI in a paired workflow",
    "manual": "Code was written exclusively by a human",
    "reviewed": "AI-generated code that received human review before merge",
}

AGENT_SKILLS = [
    ("HALF-Discovery", "Requirements elicitation"),
    ("HALF-Specification", "Technical specification"),
    ("HALF-Architect", "System architecture"),
    ("HALF-Scaffold", "Repository setup"),
    ("HALF-Implement", "Implementation"),
    ("HALF-Testing", "Test generation"),
    ("HALF-Security", "Security auditing"),
    ("HALF-Integration", "Integration testing"),
    ("HALF-Infrastructure", "IaC generation"),
    ("HALF-CICD", "Pipeline configuration"),
    ("HALF-Launch", "Production readiness"),
]


class AIDeclarationGenerator:
    """Generates AI-DECLARATION.md for a project.

    Called automatically during Phase 4 deployment to create
    or update the AI-DECLARATION.md file in the repository root.
    """

    def __init__(self, repo_path: str | Path = ".", provider: str = "openrouter"):
        self.repo_path = Path(repo_path)
        self.provider = provider

    def generate(
        self,
        declaration_level: str = "auto",
        project_name: str = "",
        phases_executed: list[str] | None = None,
        repo_url: str = "",
    ) -> str:
        """Generate AI-DECLARATION.md content.

        Args:
            declaration_level: One of auto, pair, manual, reviewed.
            project_name: The project name.
            phases_executed: Which phases were executed.
            repo_url: Repository URL.

        Returns:
            The complete AI-DECLARATION.md content.
        """
        now = datetime.now(tz=UTC)
        phases = phases_executed or ["phase-1", "phase-2", "phase-3", "phase-4"]

        # Load MRP data if available
        mrp_data = self._load_mrp()

        content = f"""# AI-DECLARATION

> **Generated by HALF — Hermes Agentic Lifecycle Framework**
> This document declares the level of AI involvement in this repository
> per the open standard for AI usage transparency.

## Declaration

```
AI-DECLARATION: {declaration_level}
```

## What This Means

**{DECLARATION_LEVELS.get(declaration_level, "Custom declaration level")}**

| Tag | Meaning |
|-----|---------|
| `AI-DECLARATION: auto` | Code autonomously generated by AI agent with human oversight |
| `AI-DECLARATION: pair` | Code co-written by human and AI |
| `AI-DECLARATION: manual` | Code written exclusively by human |
| `AI-DECLARATION: reviewed` | AI-generated code with human review before merge |

## Framework

- **Engine:** Hermes Agent (Nous Research)
- **Methodology:** Hermes Agentic Lifecycle Framework (HALF) v1.0.0
- **Phases executed:** {", ".join(phases)}
- **Inference provider:** {self.provider}
- **Human checkpoints:** Phase 1 (spec review), Phase 3 (security review), Phase 4 (Finality Gate)

## Agents Involved

| Skill | Role |
|-------|------|
"""
        for skill_name, role in AGENT_SKILLS:
            content += f"| {skill_name} | {role} |\n"

        content += f"""
## Audit Trail

- **Repository:** {repo_url or "[repo-url]"}
- **Generated at:** {now.isoformat()}
- **Last updated:** {now.isoformat()}
"""

        if mrp_data:
            checks = mrp_data.get("checks", {})
            content += """## Verification

| Check | Status |
|-------|--------|
"""
            for check_name, passed in checks.items():
                status = "✓ Passed" if passed else "✗ Failed"
                content += f"| {check_name.replace('_', ' ').title()} | {status} |\n"
        else:
            content += """## Verification

- **Status:** Pending — run Phase 4 to generate MRP
"""

        content += """\n---
*Declaration auto-generated by HALF. Update manually if AI involvement level changes.*
"""
        return content

    def write(self, content: str) -> Path:
        """Write AI-DECLARATION.md to the repository root.

        Args:
            content: The declaration content.

        Returns:
            Path to the written file.
        """
        filepath = self.repo_path / "AI-DECLARATION.md"
        filepath.write_text(content)
        logger.info("Written AI-DECLARATION.md to %s", filepath)
        return filepath

    def _load_mrp(self) -> dict[str, Any] | None:
        """Load MRP data if available."""
        mrp_file = self.repo_path / ".hale" / "artifacts" / "phase-4" / "mrp.json"
        if mrp_file.exists():
            try:
                return json.loads(mrp_file.read_text())  # type: ignore[no-any-return]
            except (json.JSONDecodeError, OSError):
                pass
        return None
