"""HALF — PDA Digest: Automated Morning Briefing.

Synthesizes overnight Ralph Loop audit results, test failures, and system
health into a concise daily update delivered via local TTS.

Based on the HALF doctrine's Commander Agent PDA capabilities.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from half.doctor import Doctor
from half.ralph_loop import RalphLoop

logger = logging.getLogger("half.pda_digest")


class PDADigest:
    """Personal Digital Assistant — automated morning briefing.

    1. Runs doctor diagnostics
    2. Executes Ralph Loop audit
    3. Synthesizes results into a concise briefing
    4. Optionally reads it aloud via TTS
    """

    def __init__(self, repo_path: str | Path = "."):
        self.repo_path = Path(repo_path)

    def generate_briefing(self) -> str:
        """Generate the morning briefing text.

        Returns:
            A concise markdown briefing of overnight results.
        """
        logger.info("PDA Digest: Generating morning briefing")

        # Run diagnostics
        doctor = Doctor()
        report = doctor.run_full_diagnostics()

        # Run Ralph Loop
        ralph = RalphLoop(self.repo_path)
        ralph_report = ralph.run()

        # Check for MRP readiness
        mrp_file = self.repo_path / ".hale" / "artifacts" / "phase-4" / "mrp.json"
        mrp_ready = mrp_file.exists()

        # Build briefing
        now = datetime.now(tz=timezone.utc)
        lines = [
            f"# HALF PDA Digest — {now.strftime('%A, %B %d, %Y')}",
            "",
            "## System Health",
            f"- **Status:** {report.overall_status.upper()}",
            f"- **Checks:** {report.summary}",
            "",
            "## Nightly Audit (Ralph Loop)",
            f"- **Findings:** {len(ralph_report.findings)}",
            f"- **Auto-fix branches:** {ralph_report.branch_count}",
            "",
        ]

        if ralph_report.findings:
            lines.append("### Key Findings")
            for f in ralph_report.findings[:5]:
                lines.append(f"- [{f.severity}] {f.category}: {f.description[:100]}")
            lines.append("")

        if mrp_ready:
            lines.append("## Deployment Ready")
            lines.append("- **MRP generated** — Finality Gate awaiting sign-off")
            lines.append("")

        # Add any CRITICAL items
        critical = [c for c in report.checks if c.severity == "critical" and not c.status]
        if critical:
            lines.append("## ⚠ Critical Issues")
            for c in critical:
                lines.append(f"- {c.name}: {c.message}")
            lines.append("")

        lines.append("---")
        lines.append("*Briefing auto-generated by HALF PDA Digest*")

        briefing = "\n".join(lines)
        logger.info("PDA Digest: Briefing generated (%d lines)", len(lines))

        return briefing

    def speak_briefing(self, text: str = "") -> None:
        """Read the briefing aloud via TTS.

        Args:
            text: If empty, generates the briefing first.
        """
        if not text:
            text = self.generate_briefing()

        # Strip markdown for speech
        import re
        plain = re.sub(r"[#*_`\[\]]", "", text)
        plain = re.sub(r"\n+", ". ", plain)

        try:
            from half.half_voice import VoiceEngine
            engine = VoiceEngine()
            if engine._tts_available:
                engine.speak(plain)
                logger.info("PDA Digest: Briefing spoken aloud")
            else:
                logger.info("PDA Digest: TTS not available — briefing printed instead")
                print(plain[:500])
        except ImportError:
            logger.info("PDA Digest: Voice module not available")
            print(plain[:500])
